---
- hosts: ec2
  remote_user: admin
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:
    ################################
    # https://wiki.debian.org/NvidiaGraphicsDrivers#Version_352.79_.28via_jessie-backports.29
    - name: add repo to sources.list
      apt_repository:
        # repo: 'deb http://httpredir.debian.org/debian jessie-backports main contrib non-free'
        repo: 'deb http://httpredir.debian.org/debian/ jessie main contrib non-free'
        state: present
        
    - name: get linux-headers package name for this system
      action: shell echo linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,')
      register: linux_headers_package_name
      
    - name: install linux-headers
      apt:
        update_cache: true
        name:
          - "{{ linux_headers_package_name.stdout }}"
          - nvidia-kernel-dkms
      register: install_nvidia_driver_state
      
      
    # - name: install nvidia-driver
    #   apt:
    #     update_cache: true
    #     # default_release: jessie-backports
    #     name:
    #       - nvidia-driver
    #   register: install_nvidia_driver_state

    # - name: remove /tmp/files

    - name: create xorg dir
      file:
        path: /etc/X11/xorg.conf.d
        state: directory

    - name: copy xorg.conf
      copy:
        content: '
Section "Device"
    Identifier "My GPU"
    Driver "nvidia"
EndSection'
        dest: /etc/X11/xorg.conf.d/20-nvidia.conf
    
    - name: restart machine
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true
      when: install_nvidia_driver_state.changed

    - name: waiting for server to come back
      local_action: wait_for host='{{ inventory_hostname }}' port=22 delay=10 timeout=300 state=started
      become: false
      when: install_nvidia_driver_state.changed

    ####################################################
    # https://github.com/NVIDIA/nvidia-docker
    # - name: download nvidia-docker
    #   get_url:
    #     url: https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3-1_amd64.deb
    #     dest: /tmp

    # - name: install nvidia-driver
    #   apt:
    #     deb: /tmp/nvidia-docker_1.0.0.rc.3-1_amd64.deb


    #############################################
    # https://github.com/NVIDIA/nvidia-docker
    - name: download nvidia-docker
      get_url:
        url: https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0-rc.3/nvidia-docker_1.0.0.rc.3_amd64.tar.xz
        dest: /tmp

    - name: asdf11
      action: shell tar --strip-components=1 -C /usr/bin -xvf /tmp/nvidia-docker*.tar.xz

    - name: asdf22
      action: shell ( ( nohup nvidia-docker-plugin > /tmp/nvidia-docker.log 2>&1 ) & ) 
      # action: shell sudo -b nohup nvidia-docker-plugin > /tmp/nvidia-docker.log 

    
    
    # - name: remove /tmp/files    



